zad1_stack : zad1_stack.o
	ld  -o zad1_stack zad1_stack.o
zad1_stack.o : zad1_stack.s
	as -gstabs -o zad1_stack.o zad1_stack.s

zad1_reg : zad1_reg.o
	ld  -o zad1_reg zad1_reg.o
zad1_reg.o : zad1_reg.s
	as -gstabs -o zad1_reg.o zad1_reg.s

zad2: zad2.o
	ld  -o zad2 zad2.o
zad2.o : zad2.s
	as -gstabs -o zad2.o zad2.s

