lab4_zad1 : lab4_zad1.o lab4_zad2 lab4_zad3 
	ld  -o lab4_zad1 lab4_zad1.o
lab4_zad1.o : lab4_zad1.s
	as -gstabs -o lab4_zad1.o lab4_zad1.s

lab4_zad2 : lab4_zad2.o
	ld  -o lab4_zad2 lab4_zad2.o
lab4_zad2.o : lab4_zad2.s
	as -gstabs -o lab4_zad2.o lab4_zad2.s

lab4_zad3 : lab4_zad3.o
	ld  -o lab4_zad3 lab4_zad3.o
lab4_zad3.o : lab4_zad3.s
	as -gstabs -o lab4_zad3.o lab4_zad3.s
